// Copyright Voxel Plugin, Inc. All Rights Reserved.

#include "VoxelISPCNodeHelpers.h"

REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Ceil_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Ceil_DoubleToInt);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Ceil_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Ceil_FloatToInt);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Floor_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Floor_DoubleToInt);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Floor_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Floor_FloatToInt);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Round_DoubleToDouble);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Round_DoubleToInt);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Round_FloatToFloat);
REGISTER_VOXEL_NODE_ISPC(VoxelMathConvertNodes, VoxelNode_Round_FloatToInt);