// Copyright Voxel Plugin, Inc. All Rights Reserved.

#include "VoxelISPCNodeHelpers.h"

REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_BooleanAND);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_BooleanNAND);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_BooleanOR);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Equal_Bool);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Equal_Byte);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Equal_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Equal_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Equal_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Greater_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Greater_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Greater_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_GreaterEqual_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_GreaterEqual_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_GreaterEqual_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Less_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Less_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_Less_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_LessEqual_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_LessEqual_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_LessEqual_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NearlyEqual_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NearlyEqual_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NotEqual_Bool);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NotEqual_Byte);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NotEqual_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NotEqual_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelBoolNodes, VoxelNode_NotEqual_Int);