// Copyright Voxel Plugin, Inc. All Rights Reserved.

#include "VoxelISPCNodeHelpers.h"

REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Abs_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Abs_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Abs_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Add_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Add_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Add_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Divide_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Divide_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Divide_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Max_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Max_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Max_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Min_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Min_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Min_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Modulus);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Multiply_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Multiply_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Multiply_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_OneMinus_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_OneMinus_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Sign_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Sign_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Sign_Int);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Subtract_Double);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Subtract_Float);
REGISTER_VOXEL_NODE_ISPC(VoxelOperatorNodes, VoxelNode_Subtract_Int);